### ISSUE TITLE
Test URL access on SP production server

### ISSUE THREAD

**Issue by aggarwalvijay** [VCHDecisionSupport/SharePoint-Admin#13]
Bonzai v 1.6 needs to access following URLs 

*.bonzaicloud.com
https://cdn.bonzaicloud.com
https://provisioner.bonzaicloud.com
https://subspace.bonzaicloud.com
https://fleet.bonzaicloud.com
https://www.google-analytics.com
https://ssl.google-analytics.com
https://track.addevent.com

use following command on command prompt on these servers and see if you are getting a reply back:

ping cdn.bonzaicloud.com 
ping provisioner.bonzaicloud.com
ping subspace.bonzaicloud.com
ping fleet.bonzaicloud.com
ping track.addevent.com

Service desk opened these URLs via SR3791531.

Please test if we are able to access these URLs on
spdbssps008
spspsfe011
spspsfe012
spspsfe013

**Comment by grahamcrowell** [comment]
ping cdn.bonzaicloud.com 52.84.239.33
    11 - works
    12 - works
    13 - works
ping provioner.bonzaicloud.com (could not find host)
    11, 12, 13
ping subspace.bonzaicloud.com
    11 - works
    12 - works
    13 - works
ping fleet.bonzaicloud.com
    11 - works
    12 - works
    13 - works
ping www.google-analytics.com
    11 - works
    12 - works
    13 - works
ping ssl.google-analytics.com
    11 - works
    12 - works
    13 - works
ping track.addevent.com (Request timed out.)
    11, 12, 13

**Comment by grahamcrowell** [comment]
sql won't need and probably shouldn't have access to or from the internet

**Comment by aggarwalvijay** [comment]
that's fair. Waiting for Kristina's reply. can you please try opening:

https://track.addevent.com

in browser

**Comment by grahamcrowell** [comment]
![image](https://cloud.githubusercontent.com/assets/8306194/25498683/d7917fca-2b3d-11e7-98c9-f0998884a2f2.png)

**Comment by aggarwalvijay** [comment]
ping provisioner.bonzaicloud.com

**Comment by aggarwalvijay** [comment]
Please test the following URLs:

ping provisioner.bonzaicloud.com 
ping track.addevent.com

**Comment by aggarwalvijay** [comment]
all URLs are working now.
